package com.example.mgdgame;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.view.View;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.List;

public class HighscoreActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_highscore);

        TextView lsScores   = findViewById(R.id.tvHighscore);
        Database db         = new Database(this);

        List<Score> mListHighscores = new ArrayList<Score>();

        mListHighscores                 = db.getAll();
        StringBuilder lsScoreString     = new StringBuilder();

        for(int i = 0; i < mListHighscores.size(); i++){

            //auto generated by android studio (Username + " " + Score + "\n")
            lsScoreString.append(mListHighscores.get(i).getUsername()).append(" ").append(mListHighscores.get(i).getScore()).append("\n");

        }

        lsScores.setText(lsScoreString.toString());
        lsScores.setMovementMethod(new ScrollingMovementMethod());

    }
    public void mainMenu(View argView){

        startActivity(new Intent(HighscoreActivity.this, MainActivity.class));
        finish();

    }
}